### ISSUE TITLE
您好，原始数据集可以提供下载吗？

### ISSUE THREAD

**Issue by kyroad** [jxm6165/Research-Azure-Audio-Only-Emotion-Detection-Model-#1]
您好，原始数据集可以提供下载吗？能否留给邮箱？

**Comment by jxm6165** [comment]
原始数据集可以从以下网址下载：
1.	RAVDESS
https://zenodo.org/record/1188976/files/Audio_Speech_Actors_01-24.zip?download=1
2.	Emo-DB
http://emodb.bilderbar.info/start.html
3.	SAVEE
http://kahlan.eps.surrey.ac.uk/savee/

如果有问题，可以用以下邮箱联系我：
jxm6165@outlook.com

**Comment by kyroad** [comment]
谢谢您


 
---原始邮件---
发件人: "jxm6165"<notifications@github.com>
发送时间: 2019年7月21日(星期日) 晚上9:54
收件人: "jxm6165/Research-Azure-Audio-Only-Emotion-Detection-Model-"<Research-Azure-Audio-Only-Emotion-Detection-Model-@noreply.github.com>;
抄送: "kyroad"<270177300@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jxm6165/Research-Azure-Audio-Only-Emotion-Detection-Model-] 您好，原始数据集可以提供下载吗？ (#1)



原始数据集可以从以下网址下载：
  
RAVDESS
 https://zenodo.org/record/1188976/files/Audio_Speech_Actors_01-24.zip?download=1 

Emo-DB
 http://emodb.bilderbar.info/start.html 

SAVEE
 http://kahlan.eps.surrey.ac.uk/savee/ 
 
如果有问题，可以用以下邮箱联系我：
 jxm6165@outlook.com
